from os import PathLike
from pathlib import Path


def bundle(
    *, include: list[str], exclude: list[str] | None = None, banner: str | None = None
) -> str:
    bundled = ''
    if banner:
        bundled += banner + '\n'

    bundled += '\n'.join(
        [
            path.read_text()
            for glob in include
            for path in Path('.').glob(glob)
            if not exclude or not any(path.full_match(ex) for ex in exclude)
        ]
    )

    if not bundled.endswith('\n'):
        bundled += '\n'
    return bundled


def build(
    *,
    outfile: PathLike,
    include: list[str],
    exclude: list[str] | None = None,
    banner: str | None = None,
) -> None:
    Path(outfile).write_text(
        bundle(include=include, exclude=exclude, banner=banner)
    )


if __name__ == '__main__':
    build(
        outfile='ushio.sty',
        include=[
            'src/header.tex',
            'src/dependencies/math.tex',
            'src/dependencies/figure.tex',
            'src/dependencies/table.tex',
            'src/dependencies/misc.tex',
            'src/environments/*.tex',
            'src/macros/*.sty',
            'src/macros/*.tex',
        ],
        banner='% This file is auto-generated by build.py. Do not edit directly.\n',
    )
